# .github/workflows/build_wheels.yml

name: Build and Release Python Wheels

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # 任务2：仅在推送标签时进行发布构建
  build_and_release:
    name: Release wheels on ${{ matrix.os }}
    # 条件：仅当触发事件是一个标签时运行
    if: github.ref_type == 'tag'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels for release
        uses: pypa/cibuildwheel@v2.19.1
        env:
          # 从 Git 标签设置版本号
          CIBW_ENVIRONMENT: LZMA_VERSION=${{ github.ref_name }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}-${{ github.ref_name }}
          path: ./wheelhouse/*.whl
      
      # 将来您可以在这里添加一个步骤，自动将 wheel 文件发布到 PyPI
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}