# .github/workflows/build_wheels.yml

name: Build Python Wheels

# 1. 何时触发：当有代码推送到主分支，或有人创建 Pull Request 时
#    新增：当一个以 'v' 开头的标签被推送时
on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*' # <-- 新增：在 v* 标签上触发
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        # 新增：设置环境变量，将版本号传递给构建过程
        env:
          # github.ref_name 会自动获取标签名 (例如 "v1.0.3")
          # 我们需要去掉开头的 'v'，所以这里假设您的 __init__.py 会处理
          # 或者更稳妥的方式是直接使用标签名
          LZMA_VERSION: ${{ github.ref_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}-${{ github.ref_name }} # <-- 让产物名称也包含版本号
          path: ./wheelhouse/*.whl